export const FIREBASE_API_KEY = 'FIREBASE_API_KEY';
export const FIREBASE_AUTH_DOMAIN = 'FIREBASE_AUTH_DOMAIN';
export const FIREBASE_DATABASE_URL = 'FIREBASE_DATABASE_URL';
export const FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID';
export const FIREBASE_STORAGE_BUCKET = 'FIREBASE_STORAGE_BUCKET';
export const FIREBASE_MESSAGING_SENDER_ID = 'FIREBASE_MESSAGING_SENDER_ID';
export const WEBSOCKET_HOST = 'localhost';
export const WEBSOCKET_PORT = 8081;
