language: node_js
node_js: 8

cache:
  directories:
    - client/node_modules

before_install:
  - cd client
  - ls
  - cp build.properties.dist.js build.properties.js

install:
  - npm install

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test
