# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
#   test:
#     docker:
#     - image: circleci/node:7.10
#     working_directory: ~/card-game-coinche
#     steps:
#       - checkout
#       - run:
#         name: run eslint
#         command: yarn lint
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/card-game-coinche

    steps:
      - checkout
      - run: ls
      - run: cd client && ls
      - run: cd client && cat package.json

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd client && yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "client/package.json" }}

      # run tests!
      - run: cd client && yarn test
